# TRMNLP configuration for Dev.to Plugin
# {{ env.VARIABLE }} interpolation is available here
---
# auto-reload when files change (`watch: false` to disable)
watch:
  - .trmnlp.yml
  - src

# values of custom fields (defined in src/settings.yml)
custom_fields:
  tag: "typescript"
  state: "fresh"
  top: 7
  show_thumbnail: true

# Time zone IANA identifier to inject into trmnl.user
# See https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
time_zone: Europe/Berlin

# override variables for local development
# variables:
#   trmnl:
#     plugin_settings:
#       instance_name: Dev.to Articles
#       custom_fields_values:
#         tag: "python"
#         state: "rising"
#         top: 30
#         show_thumbnail: true
